name: Changes badge automatically

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    # Add step to install dependencies
    - run: |
        pip install pytest
    - id: testing
      run: pytest exercise_2
      continue-on-error: true
    - if: steps.testing.conclusion == 'success'
      run: sed -i 's/https://img.shields.io/badge/tests-unknown-lightgrey/https://img.shields.io/badge/tests-passing-green/g'
    - if: steps.testing.conclusion == 'failure'
      run: sed -i 's/https://img.shields.io/badge/tests-unknown-lightgrey/https://img.shields.io/badge/tests-failing-red/g'

  